## 本地图片上传路径
local:
  path: static
mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: newbee_mall_db_v2
  username: root
  password: 123456
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
system:
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
  iplimit-count: 15000
  iplimit-time: 3600
zap:
  level: info
  format: console
  prefix: '[newbee_mall]'
  director: log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

#alipay:
#  appid: "2021004142608201"
#  aliPublic: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApSE/xVACxAT6SZpnasQLduBQ7foMEU67saJxf2guqwsdiKfNOgNFHpaxkWdySa/8Aju52OiqUM/wlKteUGP/OXaGYKXILfmuYVzNuREiY5pDJ5395l+LtEHjNleNp83/8s8529STLDxA4s/3InDSNqLybO/JNxPOuo6gPJ59d7ijK3TcOSFUqsIG6uDjjYdX2zcCoW2zkDAWI7c4DEKWa0gVoS0rgMhUvTe22gzKcBHdB8f3+XUAR3rEqxlGyn8lq4jna+WBaE4RjTx9DslYINaUB7dRHB+CZjs73SbLmIj//bXAs8gh2mRsV6Cr0Ac2uQxvGY0zKIVTCj1kUqj3WwIDAQAB"
#  aliServerUrl: "https://openapi.alipay.com/gateway.do"
#  myPrivateKey: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCVfOaGlAGQJV867cLupV9zRTedhSSMLTY7inaQYah4PBWxfUwq4aXZwAOUP6x5Kkk0lt99ybzrVe/3IidOp6uqstaNUknEjgTYIEbo3JyqYKeDCdhZ0/0KHlhqF3MIREGtUh+W4mIFtzIy0TL9Xcu7aaCQybZ75F2oBA/gBCJ2n9zAWlRoY+eCNRL2Rx3rJdVKwRgHyx1TJTOpQ/rQEeptt6GuBdvmVOkO8HH/a+9mH7T+KSXnStJxxlc4tVFuC4bUnVSse7R8cSiehENX4kHpxoaW/1F0x/R/KJva8mQCrpJyXzraYeA/eHEbjjuWm0rt6ep2kjgn5k7MVf8dXErXAgMBAAECggEAPnSJh86MfKHwkJlHqRc0st9HZit7Yol9MBEgiiATF/Dai2YzDXNrLHe5xxV3RMQzA6LJSy+fG5+y+0isrYMGCPJhC3hG07UWNwn9Nkr9tX1eXzQczSLxhGm7PNABQoHqArTd99crZwHsGiknKY4nkWyHJhbwhACcVJcl3s07bN2oET25lQYYkhdLHaCdIHXmuJL99Y1whtAqj208RBLfDmGlEHlETuLOWf+BxXZ4fWZ0L1RHcCb9+UBano3u0mGgGkALkRg/VeycMeblGRFVkUWFZVzj3pCN0FOx9eNlpcxAq/HWUvEPui/+XQ8SRIABtfWf83N4wcNh6zdgCcEUQQKBgQDEPbVZlUbPw6LF5vAS2kJEsrK2jf/xljhJCmgcktPclkii2DsS9JJZ0nBr2NZimJHymhKH9XeAZIOHRfsztfH1DUtmpwQDPoVXYozBRCZ67aBPVdmUOizgOoYQmVhayZ56z6gyJlAQ3hxanFO0tEuK05zzihBiNhOKqHE7+/+a4QKBgQDDAnkyj0a9S436xnjfSAXgP2gMG/n+HoJzHlBWnJ2pTbCA6g8RFYVdT8Lw3xX+m1tGkUxl0xlM+2jdvVX/YuJH8kU+gD9gQSWzAv/KtGkrB2CULkSb9X/SWtqjeblEkm+mUTXPterMKWfAPzVMJRL3jiNvR6bnnPJhRcFCdesUtwKBgQCSLzXMyfq6Ao5axjHImXYMHuIqQ5WJrdG391yfDHFuPTVWuaUn9bCf4LeGXz00rVrrUgLD7QNcTYP9XRBH8R2Q4ppsmbXPhN9nvS4FOnM/14w4DUfLt5p+XppH+zNqTg8UhWRSF2BFcG/Gv/VLA5PSkti0QwD5aDceb2QKvyolgQKBgF1H8JuLx6XC326Gw8jildT335hzRXkWNQZGCN31WsFipTx1ObHNXpcNEU3RGJ9KxzWRST8n5GFbnYT8DYf1UBJkRFUqWaZ8Y0Em/R6EgA4SIFOhcjY8D+Gajh1Gm6W+emPPUvNBrMfuQm/GjIMY9OKv/ik72A3QmGyJRnG5IDMvAoGAcBKjtSbOPUO9iV20VpLIC9U+e5NHNm2sMEbuID2PLjp+zrygI+nKp7Yp3CQBkd+mglHa67UNnKVOCSrVBh5Mh9GABmxWGgYngPEZ5Ba9MCXjAUbmi8fD+zTJhgaXLTbcpi+lGID984Dp6OD+9OeElZJqHye2c4iE4/p8sPRTgPQ="
#  charset: "utf-8"
#  signType: "RSA2"
#  profile: "dev"

alipay:
  appid: "9021000136632950"
  aliPublic: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnTpsKs8BtBQqVDv7afdBAAoAJKLmRhuKBwz+TKK5Rrw8kYQAlJEKYfNoj4q2DjfDvJz9NvLCTnQsis7VXqwWDecTWEkdGmohKmd/CtPnASMf2YN7ruZCNgaCk5epxVZyIiEotcmsY5G7G5bUSdGyaLS1/A166DLfBkco0h5NC/n1w1fhj+8Kv5W5uFtRxkXeybJH/XJGCU3Xcb5R9a+nbo9iHBp3AMAK/4zmzPoe1ZkunufK//QGaFqAZfPJBPJvLVN5HUCSjqSeHKf3IYs095XGvQF8MUbhHGGqsk/CDqt7FtITCt7FOz7tlAYnHLBWlD388HHjfmiJkSJhyVxPhQIDAQAB"
  aliServerUrl: "https://openapi.alipay.com/gateway.do"
  myPrivateKey: "MIIEpQIBAAKCAQEAtB8qP/KfzJAP2jzY7G1Y+IM8aqTK/Mas7pEAi+BS9AmhPSoHHlnf2hhiPQIPkQMdlCEmnzzZCVvjiHybFGsqLvgVP+vkQc+oBXwJyvwjnBsGwgjeBckQo/7bg6+ppgJ8URw+ouGd3YXMEOLv3VQORxVsnywTMTgIyvWxBwWjobWf/jycyOMQg9RidLzhPpqw5ICXfE83o5iX9iopFu1r//orEAkKE+qAhaBO3x+FCbd2LVyh/cXvIolZmXo5a3VOq+E9s/ts4T2S27hYmDmHzTOGHy0+MIi8HrmLZD/qMrL0JI3tu10iHzY5EPWUzxxD+LxNr2VK2MtPyxPtZiXVCwIDAQABAoIBAAvlIv0mILd5rBJVgl3aus1unUbNqzoWRMVcfhS+s7u6BxPq+p1eghH9Gj+9KxoAgquNpOdPNWYQ023oDLXEffysFXsrMN/Hvujd0Ce/jvp4LnIR89ed96Nc6VJA/4sfDuasXtaS38IJW/ihhAWxz1+SYqIAXyQY9zuwDgjQroW3RFV3nfnqpnwwmcxlvqHUC8dw3q/aBNS6aaLHOwJ8guzE5X66DDicCv+/9LmjdvDf7AXqK6nG8ffQQlt+LfPPMArOP1k9KIFfZjZARifvT6W2cm1hH7pSoM9cb1UQMQyh3Kw3JCe9mjvqM64BLHcxtuLQO2K87s3SXVpp+iyM6UECgYEA8LgYRX92daAOJnob6X4ah+RG010HuKggYQXueUsKC0616mx3aiauOn+PSZ55/H7S+3MtB35HCXdbx3ttj6InPjLMEJbbILGn98f7wZXCltswnGJZomMyclPSLooOo4eqPxXJTU9sYGwm49ebbRbZqqSO2ohXUZqs61+n172OrNcCgYEAv45OuZ8JNbGrYYoI5GBIdt9MzgRD6Bs39Ntcd9uINCLYOr8KlsddLxX6/R0lQzLx6ZViJHAy9sb3Bk1WZYc59lRGQulH8Ws2hICpZrspXImMIdJiNlV6igei04lNx5DV/3alX6jhBjkviMpWOTTRnkQkF6ZTcUWe6g1LosIyfu0CgYEAxq5r+hC2aWdtxnxKxXF73GWhv5qtYNADyZDnv90bsTGKHK7h8Q90Bnx6e7z92lWjNj9eDy0+3KVTb1aEm2SvFzs+CwM4YcfAZ1b8iE9fiLvpZ2oVqV5OqOZeOGNiqb6z2dXVjKXdQciCYNP4SRXvGlUwQ1b9GzGbP7p4Ai1GsYkCgYEAod2LspirvJ6UlkiA+RJPSXupuBCsnS6a2yKeAX4VmxCyrPmP5hczK72kKEx/l0guWVZs5yOUPSmlxcKGNibNmNRfxty/eUZCfDcIbpHLArIMIuxXJ1iVwptvQNcuTWubGVLVrX7UH2ElRK7Nq2txkg48fWuD6RyOi3KOrkrxRoUCgYEAnDlwXH4iN3RK/oh4goghS+DWQt0OzDFnum1eBouIn8WMrTEJn5YkI0JHY5C+vGtcZUkYThGw5N03lR1f/o2rTV1JQoDEN9JFKzok7mB6Ffbt8RqOhEDL7nyWZGhKtQKXiVUkooHGHCe5vkCpLXMGF/be6EwwSqzLxtK9CASE2MA="
  charset: "utf-8"
  signType: "RSA2"
  profile: "dev"









